[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "Hypick"
name = "AdrenalineRush"
description = "Fork mod Rush Of Adrenaline. Increases the player's speed and FOV by a multiplier when they enter a state of fear (Fully configurable)"
websiteUrl = "https://github.com/Hypick122/AdrenalineRush"
containsNsfwContent = false

[package.dependencies]
# https://thunderstore.io/c/lethal-company/p/BepInEx/BepInExPack/
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "icon.png"
readme = "README.md"
outdir = "build"

[[build.copy]]
source = "AdrenalineRush/bin/Hypick.AdrenalineRush.dll"
target = "BepInEx/plugins/AdrenalineRush.dll"

[[build.copy]]
source = "CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "LICENSE"
target = "LICENSE"

[publish]
communities = ["lethal-company"]

[publish.categories]
# The categories are available at https://thunderstore.io near of the search bar
# https://thunderstore.io/api/experimental/community/lethal-company/category/
lethal-company = ["bepinex", "mods", "serverside", "misc"]
